"""
Verifier for the structured-mrr-rebuild task.

All expected values are derived from the deterministic synthetic dataset
generated by environment/data/build_inputs.py. Tests are fully deterministic
and do not use LLM-as-judge.

Dataset: 25 accounts, 60 invoice lines (incl. 2 non-adjacent duplicates),
3 reporting months (2026-01 to 2026-03), 4 currencies (USD, EUR, CAD, GBP).
Expected output: 46 account-month rows, total MRR 32,549.19.

String normalisation traps:
  sub_002 billing_interval = "Annual"  (capital A) — divisor lookup fails without str.lower()
  il_025  line_type        = "Subscription" (capital S) — filter fails without str.lower()
  il_045  amount           = "$319.00" (currency string) — parse fails without stripping $

Aggregate summary traps:
  max_mrr_account_id = "acct_022" (total 3375.00 across 3 months, not acct_010 single-row peak)
  max_mrr_month      = "2026-01"  (aggregate 13459.58, not "2026-02" which has the highest row)
"""

from __future__ import annotations

import json
from pathlib import Path

import pandas as pd
import pytest

PARQUET_PATH  = Path("/root/out/mrr_by_account.parquet")
JSON_PATH     = Path("/root/out/mrr_summary.json")
MONTHLY_PATH  = Path("/root/out/monthly_summary.csv")

REQUIRED_PARQUET_COLS = {"account_id", "customer_name", "month", "mrr_usd", "source_line_count"}
REQUIRED_JSON_KEYS    = {
    "total_mrr_usd", "account_count", "month_count",
    "max_mrr_account_id", "max_mrr_month",
    "excluded_non_recurring_total_usd", "tax_excluded_total_usd",
}

TOLERANCE = 0.01

# ── Expected MRR per (account_id, month) ──────────────────────────────────────
# Derivation notes are in build_inputs.py. All amounts are in USD.
#
# Trap accounts:
#   acct_001 Jan/Feb/Mar: 523.75 each          — baseline monthly USD, recurring
#   acct_002 Jan:         1123.00               — annual USD 13476÷12
#   acct_003 Feb:         1299.60               — annual EUR 14400÷12 × EUR-Feb 1.0830
#   acct_004 Jan/Feb:     731.45 each           — pre-tax only; tax_amount 95.09 excluded
#   acct_005 Jan:          489.20               — setup_fee 2500 + prof_svc 1950 excluded
#   acct_006 Jan:          708.48               — 960 " CAD" × 0.7380; strip whitespace
#   acct_006 Feb:          720.96               — 960 " CAD" × 0.7510
#   acct_006 Mar:          714.72               — 960 " CAD" × 0.7445
#   acct_007 Jan:          617.50               — il_014 appears twice; dedup required
#   acct_008 Feb:          875.00               — invoice_date Jan-30, service_start Feb-01
#   acct_009 Jan:         1312.50               — base 1050 + proration 262.50; prof_svc excluded
#   acct_010 Feb:         1652.20               — annual CAD 26400÷12 × CAD-Feb 0.7510
#   acct_011 Jan:         1012.50               — base 1350 + downgrade credit -337.50
#
# New trap accounts:
#   acct_012 Jan:          645.00               — multi-month: base only
#   acct_012 Feb:          860.00               — multi-month: base 645 + upgrade 215
#   acct_012 Mar:          752.50               — multi-month: base 860 + downgrade -107.50
#   acct_013 Jan:         1285.00               — multi-sub: core 890 + addon 245 + support 150
#   acct_013 Feb:          890.00               — multi-sub: only core renews
#   acct_013 Mar:          890.00               — multi-sub: only core renews
#   acct_014 Jan:          464.00               — quarterly USD 1392÷3; NOT in Feb/Mar despite service_end Mar
#   acct_015 Jan/Feb/Mar:  425.00 each          — catchup billing; invoice_date Mar for all 3 lines
#   acct_016 Mar:         1006.40               — annual GBP 9600÷12 × GBP-Mar 1.2580
#
# Noise accounts (same rules, realistic data):
#   acct_017 Jan/Mar:      398.00 each          — usage 125.50 excluded in Mar
#   acct_018 Feb:          586.99               — 542 EUR × 1.0830
#   acct_018 Mar:          591.86               — 542 EUR × 1.0920
#   acct_019 Jan:          745.00               — annual 8940÷12; il_041 appears twice
#   acct_020 Jan:          457.56               — 620 CAD × 0.7380
#   acct_020 Feb:          465.62               — 620 CAD × 0.7510
#   acct_020 Mar:          461.59               — 620 CAD × 0.7445
#   acct_021 Jan/Feb/Mar:  319.00 each
#   acct_022 Jan/Feb/Mar: 1125.00 each          — setup_fee 500 excluded in Jan
#   acct_023 Mar:          857.22               — 785 EUR × 1.0920
#   acct_024 Jan/Feb/Mar:  275.00 each
#   acct_025 Jan:          802.64               — annual GBP 7620÷12 × GBP-Jan 1.2640

EXPECTED_MRR = {
    ("acct_001", "2026-01"):  523.75,
    ("acct_001", "2026-02"):  523.75,
    ("acct_001", "2026-03"):  523.75,
    ("acct_002", "2026-01"): 1123.00,
    ("acct_003", "2026-02"): 1299.60,
    ("acct_004", "2026-01"):  731.45,
    ("acct_004", "2026-02"):  731.45,
    ("acct_005", "2026-01"):  489.20,
    ("acct_006", "2026-01"):  708.48,
    ("acct_006", "2026-02"):  720.96,
    ("acct_006", "2026-03"):  714.72,
    ("acct_007", "2026-01"):  617.50,
    ("acct_008", "2026-02"):  875.00,
    ("acct_009", "2026-01"): 1312.50,
    ("acct_010", "2026-02"): 1652.20,
    ("acct_011", "2026-01"): 1012.50,
    ("acct_012", "2026-01"):  645.00,
    ("acct_012", "2026-02"):  860.00,
    ("acct_012", "2026-03"):  752.50,
    ("acct_013", "2026-01"): 1285.00,
    ("acct_013", "2026-02"):  890.00,
    ("acct_013", "2026-03"):  890.00,
    ("acct_014", "2026-01"):  464.00,
    ("acct_015", "2026-01"):  425.00,
    ("acct_015", "2026-02"):  425.00,
    ("acct_015", "2026-03"):  425.00,
    ("acct_016", "2026-03"): 1006.40,
    ("acct_017", "2026-01"):  398.00,
    ("acct_017", "2026-03"):  398.00,
    ("acct_018", "2026-02"):  586.99,
    ("acct_018", "2026-03"):  591.86,
    ("acct_019", "2026-01"):  745.00,
    ("acct_020", "2026-01"):  457.56,
    ("acct_020", "2026-02"):  465.62,
    ("acct_020", "2026-03"):  461.59,
    ("acct_021", "2026-01"):  319.00,
    ("acct_021", "2026-02"):  319.00,
    ("acct_021", "2026-03"):  319.00,
    ("acct_022", "2026-01"): 1125.00,
    ("acct_022", "2026-02"): 1125.00,
    ("acct_022", "2026-03"): 1125.00,
    ("acct_023", "2026-03"):  857.22,
    ("acct_024", "2026-01"):  275.00,
    ("acct_024", "2026-02"):  275.00,
    ("acct_024", "2026-03"):  275.00,
    ("acct_025", "2026-01"):  802.64,
}

# Total MRR = 32,549.19
#   acct_014 old (cad monthly): $1,116.75 → new (quarterly USD): $464.00  (delta: -$652.75)
# excluded_non_recurring = acct_005 (2500+1950) + acct_009 (1800)
#                        + acct_017 (125.50 usage) + acct_022 (500 setup_fee) = 6,875.50
# tax_excluded = acct_004 Jan (95.09) + acct_004 Feb (95.09) = 190.18
EXPECTED_SUMMARY = {
    "total_mrr_usd":                    32549.19,
    "account_count":                    25,
    "month_count":                      3,
    # max_mrr_account_id: account with highest TOTAL MRR across all months.
    # acct_022: 1125.00 × 3 months = 3375.00 — beats acct_010's single-month peak of 1652.20.
    # Wrong answer "acct_010" means idxmax() on single rows was used instead of groupby.sum().idxmax()
    "max_mrr_account_id":               "acct_022",
    # max_mrr_month: month with highest AGGREGATE MRR across all accounts.
    # 2026-01 aggregate = 13459.58 (19 accounts) — beats 2026-02 at 10749.57.
    # Wrong answer "2026-02" means idxmax() on single rows was used instead of groupby.sum().idxmax()
    "max_mrr_month":                    "2026-01",
    "excluded_non_recurring_total_usd": 6875.50,
    "tax_excluded_total_usd":           190.18,
}

# ── Expected monthly_summary.csv values ───────────────────────────────────────
# mrr_change_usd and mrr_change_pct are NaN / absent for the first month.
EXPECTED_MONTHLY = [
    {"month": "2026-01", "total_mrr_usd": 13459.58, "account_count": 19,
     "mrr_change_usd": None,     "mrr_change_pct": None},
    {"month": "2026-02", "total_mrr_usd": 10749.57, "account_count": 14,
     "mrr_change_usd": -2710.01, "mrr_change_pct": -0.2013},
    {"month": "2026-03", "total_mrr_usd":  8340.04, "account_count": 13,
     "mrr_change_usd": -2409.53, "mrr_change_pct": -0.2242},
]


def load_parquet() -> pd.DataFrame:
    assert PARQUET_PATH.exists(), f"Missing required output: {PARQUET_PATH}"
    return pd.read_parquet(PARQUET_PATH)


def load_summary() -> dict:
    assert JSON_PATH.exists(), f"Missing required output: {JSON_PATH}"
    with open(JSON_PATH) as f:
        return json.load(f)


def load_monthly() -> pd.DataFrame:
    assert MONTHLY_PATH.exists(), f"Missing required output: {MONTHLY_PATH}"
    return pd.read_csv(MONTHLY_PATH)


def mrr_lookup(df: pd.DataFrame) -> dict:
    return {
        (row["account_id"], row["month"]): float(row["mrr_usd"])
        for _, row in df.iterrows()
    }


class TestOutputFiles:
    def test_required_output_files_exist(self):
        """All three required output files must be present at the correct paths."""
        assert PARQUET_PATH.exists(),  f"Missing: {PARQUET_PATH}"
        assert JSON_PATH.exists(),     f"Missing: {JSON_PATH}"
        assert MONTHLY_PATH.exists(),  f"Missing: {MONTHLY_PATH}"


class TestSchema:
    def test_parquet_columns_exact(self):
        """Parquet must have exactly the required columns — no extras, none missing."""
        df      = load_parquet()
        actual  = set(df.columns)
        missing = REQUIRED_PARQUET_COLS - actual
        extra   = actual - REQUIRED_PARQUET_COLS
        assert not missing, f"Missing parquet columns: {missing}"
        assert not extra,   f"Extra parquet columns (remove them): {extra}"

    def test_json_keys_exact(self):
        """JSON summary must have exactly the required keys — no extras, none missing."""
        summary = load_summary()
        actual  = set(summary.keys())
        missing = REQUIRED_JSON_KEYS - actual
        extra   = actual - REQUIRED_JSON_KEYS
        assert not missing, f"Missing JSON keys: {missing}"
        assert not extra,   f"Extra JSON keys (remove them): {extra}"

    def test_no_duplicate_account_month_rows(self):
        """Each (account_id, month) pair must appear exactly once."""
        df        = load_parquet()
        max_count = df.groupby(["account_id", "month"]).size().max()
        assert max_count == 1, (
            f"Duplicate account-month rows found (max group size = {max_count})"
        )

    def test_output_row_count(self):
        """Parquet must contain exactly 46 account-month rows."""
        df = load_parquet()
        assert len(df) == 46, (
            f"Expected 46 account-month rows, got {len(df)}. "
            f"Wrong month assignment (invoice vs service date) or missed grouping can cause extra/missing rows."
        )


class TestMRRValues:
    def test_all_account_month_mrr_values(self):
        """Every expected account-month MRR value must match within tolerance."""
        df     = load_parquet()
        lookup = mrr_lookup(df)
        errors = []
        for (acct, month), expected in EXPECTED_MRR.items():
            actual = lookup.get((acct, month))
            if actual is None:
                errors.append(f"  Missing row: ({acct}, {month})")
            elif abs(actual - expected) > TOLERANCE:
                errors.append(
                    f"  ({acct}, {month}): expected {expected:.2f}, got {actual:.2f}"
                )
        assert not errors, "Account-month MRR mismatches:\n" + "\n".join(errors)

    def test_annual_subscription_normalized_to_monthly(self):
        """Annual subscriptions must be divided by 12, not counted as a full-year amount.
        Quarterly subscriptions (÷3) are tested separately in test_quarterly_subscription_normalized_to_monthly."""
        lookup = mrr_lookup(load_parquet())
        # acct_002: 13476 USD annual → 1123.00/month
        v2 = lookup.get(("acct_002", "2026-01"))
        assert v2 is not None, "acct_002 missing from 2026-01"
        assert abs(v2 - 1123.00) <= TOLERANCE, (
            f"acct_002 annual not normalized: expected 1123.00, got {v2} "
            f"(13476.00 would mean annual was not divided by 12)"
        )
        # acct_010: 26400 CAD annual → 2200 CAD/month → 1652.20 USD at 0.7510
        v10 = lookup.get(("acct_010", "2026-02"))
        assert v10 is not None, "acct_010 missing from 2026-02"
        assert abs(v10 - 1652.20) <= TOLERANCE, (
            f"acct_010 annual CAD not normalized correctly: expected 1652.20, got {v10}"
        )
        # acct_025: 7620 GBP annual → 635 GBP/month → 802.64 USD at GBP-Jan 1.2640
        v25 = lookup.get(("acct_025", "2026-01"))
        assert v25 is not None, "acct_025 missing from 2026-01"
        assert abs(v25 - 802.64) <= TOLERANCE, (
            f"acct_025 annual GBP not normalized: expected 802.64, got {v25}"
        )

    def test_service_month_fx_rate_used_not_invoice_month(self):
        """FX rate must be looked up using the service month, not the invoice month.

        acct_003: annual EUR 14400, invoice Jan (EUR=1.1050), service Feb (EUR=1.0830).
        Correct: 14400/12 × 1.0830 = 1299.60  (service-month FX)
        Wrong:   14400/12 × 1.1050 = 1326.00  (invoice-month FX)

        acct_016: annual GBP 9600, invoice Feb (GBP=1.2710), service Mar (GBP=1.2580).
        Correct:  9600/12 × 1.2580 = 1006.40  (service-month FX)
        Wrong:    9600/12 × 1.2710 = 1016.80  (invoice-month FX)
        """
        lookup = mrr_lookup(load_parquet())

        v3 = lookup.get(("acct_003", "2026-02"))
        assert v3 is not None, (
            "acct_003 missing from 2026-02 — may be in wrong month or FX join failed"
        )
        assert abs(v3 - 1299.60) <= TOLERANCE, (
            f"acct_003 FX or annual normalization wrong: expected 1299.60, got {v3} "
            f"(1326.00 = invoice-month FX; 15552.00 = annual not divided by 12)"
        )
        assert abs(v3 - 1326.00) > TOLERANCE, (
            "acct_003 matches invoice-month FX (1326.00) — must use service-month rate"
        )

        v16 = lookup.get(("acct_016", "2026-03"))
        assert v16 is not None, (
            "acct_016 missing from 2026-03 — invoice_date Feb may have been used instead of service_start Mar, "
            "or GBP FX join failed"
        )
        assert abs(v16 - 1006.40) <= TOLERANCE, (
            f"acct_016 GBP FX wrong: expected 1006.40, got {v16} "
            f"(1016.80 = invoice-month Feb FX; 11520.00 = annual not divided by 12)"
        )

    def test_fx_whitespace_normalization(self):
        """Currency field leading whitespace must be stripped before FX join.

        acct_006: currency stored as ' CAD' (leading space) in all 3 months.
        Without stripping, the join produces NaN rates and MRR fails or becomes 0.
        Jan: 960 × 0.7380 = 708.48; Feb: 960 × 0.7510 = 720.96; Mar: 960 × 0.7445 = 714.72
        """
        lookup = mrr_lookup(load_parquet())
        for month, expected in [("2026-01", 708.48), ("2026-02", 720.96), ("2026-03", 714.72)]:
            v = lookup.get(("acct_006", month))
            assert v is not None, (
                f"acct_006 missing from {month} — FX join may have failed due to whitespace in currency"
            )
            assert abs(v - expected) <= TOLERANCE, (
                f"acct_006 {month} FX not applied correctly: expected {expected}, got {v} "
                f"(960.00 would mean FX was skipped; NaN/0 means join failed)"
            )
            assert abs(v - 960.00) > TOLERANCE, (
                f"acct_006 {month} matches unconverted CAD amount — FX join or whitespace strip failed"
            )

    def test_quarterly_subscription_normalized_to_monthly(self):
        """Quarterly subscriptions must be divided by 3 to get monthly MRR.

        acct_014: billing_interval='quarterly', amount=1392.00 USD, service_start 2026-01-01,
        service_end 2026-03-31.
        Correct: 1392 ÷ 3 = 464.00 in 2026-01 only (service_start month).
        Wrong:   1392.00 in Jan (no quarterly normalisation).
        Wrong:   464.00 in Jan + Feb + Mar (amount spread across service_end period — revenue
                 belongs in service_start month only, same rule as annual subscriptions).

        Quarterly billing is standard in enterprise SaaS (HubSpot, Salesforce, etc.).
        The instruction defines MRR as 'normalized monthly value' — this applies to
        quarterly contracts just as it applies to annual ones.
        """
        lookup = mrr_lookup(load_parquet())
        v = lookup.get(("acct_014", "2026-01"))
        assert v is not None, "acct_014 missing from 2026-01"
        assert abs(v - 464.00) <= TOLERANCE, (
            f"acct_014 quarterly not normalized: expected 464.00, got {v} "
            f"(1392.00 = quarterly amount not divided by 3)"
        )
        assert ("acct_014", "2026-02") not in lookup, (
            "acct_014 incorrectly appears in 2026-02 — quarterly MRR should be placed in "
            "service_start month only (2026-01), not spread across service_end period"
        )
        assert ("acct_014", "2026-03") not in lookup, (
            "acct_014 incorrectly appears in 2026-03 — quarterly MRR should be placed in "
            "service_start month only (2026-01), not spread across service_end period"
        )

    def test_catchup_billing_distributes_to_service_months(self):
        """A single catchup invoice with multiple service months must be split by service_start.

        acct_015: one invoice (inv_024, invoice_date 2026-03-01) contains 3 lines:
          line 1 → service_start 2026-01-01 → revenue in Jan
          line 2 → service_start 2026-02-01 → revenue in Feb
          line 3 → service_start 2026-03-01 → revenue in Mar
        This happens when a customer converts from trial to paid and is invoiced retroactively,
        or when a billing system processes arrears in batch.

        Wrong: all revenue in 2026-03 because invoice_date = March → 1275.00 in one row.
        Correct: 425.00 in each of 2026-01, 2026-02, 2026-03.
        Each output row must have source_line_count = 1 (one invoice line per service month).
        """
        df     = load_parquet()
        lookup = mrr_lookup(df)

        for month in ["2026-01", "2026-02", "2026-03"]:
            v = lookup.get(("acct_015", month))
            assert v is not None, (
                f"acct_015 missing from {month} — catchup invoice lines may be grouped by "
                f"invoice_date (March) instead of service_start"
            )
            assert abs(v - 425.00) <= TOLERANCE, (
                f"acct_015 {month}: expected mrr_usd=425.00, got {v}"
            )

        v_mar = lookup.get(("acct_015", "2026-03"))
        assert v_mar is not None and abs(v_mar - 425.00) <= TOLERANCE, (
            f"acct_015 March should be 425.00 (one line), not 1275.00 (all 3 lumped): got {v_mar}"
        )

        # source_line_count must be 1 for each month — confirms the agent split the invoice by
        # service_start rather than grouping all 3 lines into a single March row (count=3).
        acct15 = df[df["account_id"] == "acct_015"].set_index("month")
        for month in ["2026-01", "2026-02", "2026-03"]:
            if month in acct15.index:
                slc = int(acct15.loc[month, "source_line_count"])
                assert slc == 1, (
                    f"acct_015 {month}: source_line_count={slc}, expected 1. "
                    f"A count of 3 in March means all 3 catchup lines were grouped by "
                    f"invoice_date instead of service_start."
                )

    def test_tax_excluded_from_mrr(self):
        """Tax amounts on subscription lines must not be added to MRR.

        acct_004: 731.45 USD subscription + 95.09 USD tax → MRR = 731.45 (not 826.54).
        Rule applies in both Jan and Feb.
        """
        lookup = mrr_lookup(load_parquet())
        for month in ["2026-01", "2026-02"]:
            v = lookup.get(("acct_004", month))
            assert v is not None, f"acct_004 missing from {month}"
            assert abs(v - 731.45) <= TOLERANCE, (
                f"acct_004 {month} tax may be included in MRR: expected 731.45, got {v} "
                f"(826.54 would mean tax_amount was added)"
            )

    def test_compound_non_recurring_exclusion(self):
        """Both setup_fee and professional_services on the same invoice must be excluded."""
        lookup = mrr_lookup(load_parquet())
        v = lookup.get(("acct_005", "2026-01"))
        assert v is not None, "acct_005 missing from 2026-01"
        assert abs(v - 489.20) <= TOLERANCE, (
            f"acct_005 non-recurring fees may be included: expected 489.20, got {v} "
            f"(2989.20 = setup_fee included; 4439.20 = both fee types included)"
        )

    def test_revenue_month_from_service_period_not_invoice_date(self):
        """Revenue month must come from service_start, not invoice_date.

        acct_008: invoice_date = 2026-01-30, service_start = 2026-02-01.
        acct_016: invoice_date = 2026-02-28, service_start = 2026-03-01.
        """
        lookup = mrr_lookup(load_parquet())

        assert ("acct_008", "2026-02") in lookup, (
            "acct_008 missing from 2026-02 — revenue month may have been read from invoice_date Jan"
        )
        assert ("acct_008", "2026-01") not in lookup, (
            "acct_008 incorrectly appears in 2026-01 — invoice_date used instead of service_start"
        )
        v8 = lookup[("acct_008", "2026-02")]
        assert abs(v8 - 875.00) <= TOLERANCE, f"acct_008 2026-02: expected 875.00, got {v8}"

        assert ("acct_016", "2026-03") in lookup, (
            "acct_016 missing from 2026-03 — revenue month may have been read from invoice_date Feb"
        )
        assert ("acct_016", "2026-02") not in lookup, (
            "acct_016 incorrectly appears in 2026-02 — invoice_date used instead of service_start"
        )

    def test_duplicate_invoice_lines_deduplicated(self):
        """Each invoice_line_id must be counted once even if exported multiple times.

        il_014 (acct_007): appears at row 14 and again at row 59 — 37 rows apart.
        il_041 (acct_019): appears at row 41 and again at row 60 — 19 rows apart.
        Non-adjacent placement tests that agents deduplicate the full dataset, not just
        adjacent rows.
        """
        lookup = mrr_lookup(load_parquet())

        v7 = lookup.get(("acct_007", "2026-01"))
        assert v7 is not None, "acct_007 missing from 2026-01"
        assert abs(v7 - 617.50) <= TOLERANCE, (
            f"acct_007 duplicate not removed: expected 617.50, got {v7} "
            f"(1235.00 would mean the duplicate row was counted twice)"
        )

        v19 = lookup.get(("acct_019", "2026-01"))
        assert v19 is not None, "acct_019 missing from 2026-01"
        assert abs(v19 - 745.00) <= TOLERANCE, (
            f"acct_019 duplicate not removed: expected 745.00, got {v19} "
            f"(1490.00 would mean the duplicate annual row was counted twice, then ÷12)"
        )

    def test_compound_proration_with_professional_services(self):
        """Prorated subscription lines count; professional_services on same invoice must not."""
        lookup = mrr_lookup(load_parquet())
        v = lookup.get(("acct_009", "2026-01"))
        assert v is not None, "acct_009 missing from 2026-01"
        assert abs(v - 1312.50) <= TOLERANCE, (
            f"acct_009 compound case wrong: expected 1312.50, got {v} "
            f"(1050.00 = proration dropped; 3112.50 = professional_services included)"
        )

    def test_negative_subscription_adjustment_included(self):
        """Negative mid-cycle subscription credits must be included, not filtered out.

        acct_011: base 1350 USD + downgrade credit -337.50 USD = net MRR 1012.50 USD.
        Filtering amount > 0 silently drops the credit and yields 1350 instead of 1012.50.
        """
        lookup = mrr_lookup(load_parquet())
        v = lookup.get(("acct_011", "2026-01"))
        assert v is not None, "acct_011 missing from 2026-01"
        assert abs(v - 1012.50) <= TOLERANCE, (
            f"acct_011 negative credit not included: expected 1012.50, got {v} "
            f"(1350.00 would mean negative subscription line was dropped)"
        )
        assert abs(v - 1350.0) > TOLERANCE, (
            "acct_011 matches naive amount>0 filter (1350.00) — downgrade credit was dropped"
        )

    def test_currency_formatted_amount_parsed(self):
        """Currency-formatted amount strings must be parsed to numeric before MRR calc.

        acct_021 Jan: il_045 amount exported as '$319.00' string.
        Without parsing: row missing or MRR = 0; correct: 319.00.
        """
        lookup = mrr_lookup(load_parquet())
        v = lookup.get(("acct_021", "2026-01"))
        assert v is not None, (
            "acct_021 missing from 2026-01 — currency-formatted amount may not have been parsed"
        )
        assert abs(v - 319.00) <= TOLERANCE, (
            f"acct_021 Jan: expected 319.00, got {v} (raw '$319.00' string not parsed)"
        )

    def test_multi_month_account_continuity(self):
        """Same account must be correctly grouped across all months with prorations and credits.

        acct_012:
          Jan → 645.00   (base only)
          Feb → 860.00   (base 645 + upgrade proration 215)
          Mar → 752.50   (post-upgrade base 860 + downgrade credit -107.50)

        Tests that agents aggregate ALL subscription lines for each (account, month)
        pair, including prorations and negative adjustments, across a multi-month span.
        """
        lookup = mrr_lookup(load_parquet())
        for month, expected in [("2026-01", 645.00), ("2026-02", 860.00), ("2026-03", 752.50)]:
            v = lookup.get(("acct_012", month))
            assert v is not None, f"acct_012 missing from {month}"
            assert abs(v - expected) <= TOLERANCE, (
                f"acct_012 {month}: expected {expected}, got {v}"
            )

    def test_multi_subscription_aggregation(self):
        """Multiple subscriptions for the same account must combine into one MRR row per month.

        acct_013 Jan: sub_013a (890) + sub_013b (245) + sub_013c (150) = 1285.00
        acct_013 Feb/Mar: only sub_013a (890) renews → MRR = 890.00

        Tests that agents group by (account_id, month), not by subscription_id.
        A grain mistake (one row per subscription per month) would produce 3 rows in Jan.
        """
        lookup = mrr_lookup(load_parquet())
        for month, expected in [("2026-01", 1285.00), ("2026-02", 890.00), ("2026-03", 890.00)]:
            v = lookup.get(("acct_013", month))
            assert v is not None, f"acct_013 missing from {month}"
            assert abs(v - expected) <= TOLERANCE, (
                f"acct_013 {month}: expected {expected}, got {v} "
                f"(sub-level grain error would split into multiple rows instead of one)"
            )


class TestSummary:
    def test_summary_totals(self):
        """All summary metrics must match expected computed values.

        max_mrr_account_id and max_mrr_month require GROUP-BY aggregation, not
        single-row idxmax(). Common wrong answers:
          max_mrr_account_id='acct_010' → used df['mrr_usd'].idxmax() (row max, not account total)
          max_mrr_month='2026-02'       → used df['mrr_usd'].idxmax() (row max, not month aggregate)
        """
        summary = load_summary()
        errors  = []
        for key, expected in EXPECTED_SUMMARY.items():
            actual = summary.get(key)
            if actual is None:
                errors.append(f"  Missing key: {key}")
                continue
            if isinstance(expected, float):
                if abs(float(actual) - expected) > TOLERANCE:
                    errors.append(f"  {key}: expected {expected}, got {actual}")
            elif isinstance(expected, int):
                if int(actual) != expected:
                    errors.append(f"  {key}: expected {expected}, got {actual}")
            else:
                if str(actual) != str(expected):
                    if key == "max_mrr_account_id":
                        errors.append(
                            f"  {key}: expected {expected!r}, got {actual!r} "
                            f"('acct_010' = single-row max; correct = account with highest total across all months)"
                        )
                    elif key == "max_mrr_month":
                        errors.append(
                            f"  {key}: expected {expected!r}, got {actual!r} "
                            f"('2026-02' = month of highest single row; correct = month with highest aggregate)"
                        )
                    else:
                        errors.append(f"  {key}: expected {expected!r}, got {actual!r}")
        assert not errors, "Summary mismatches:\n" + "\n".join(errors)

    def test_excluded_non_recurring_covers_all_fee_types(self):
        """Excluded non-recurring must include setup_fee, professional_services, and usage amounts."""
        summary  = load_summary()
        excluded = float(summary["excluded_non_recurring_total_usd"])
        # acct_005: setup_fee 2500 + professional_services 1950 = 4450
        # acct_009: professional_services 1800
        # acct_017: usage 125.50
        # acct_022: setup_fee 500
        # total = 6875.50
        assert abs(excluded - 6875.50) <= TOLERANCE, (
            f"excluded_non_recurring_total_usd: expected 6875.50, got {excluded} "
            f"(4450.00 = only acct_005; 6250.00 = acct_017 usage missed; 6375.50 = acct_022 setup_fee missed)"
        )

    def test_tax_excluded_total_across_all_months(self):
        """Tax excluded total must equal the sum of tax_amount on subscription lines, all months."""
        summary = load_summary()
        tax     = float(summary["tax_excluded_total_usd"])
        # acct_004 Jan: tax_amount 95.09 + acct_004 Feb: tax_amount 95.09 = 190.18
        assert abs(tax - 190.18) <= TOLERANCE, (
            f"tax_excluded_total_usd: expected 190.18, got {tax} "
            f"(95.09 would mean only one month's tax was counted)"
        )


class TestMonthlySummary:
    def test_monthly_summary_schema(self):
        """monthly_summary.csv must have exactly the required columns."""
        df = load_monthly()
        required = {"month", "total_mrr_usd", "account_count", "mrr_change_usd", "mrr_change_pct"}
        missing  = required - set(df.columns)
        extra    = set(df.columns) - required
        assert not missing, f"monthly_summary.csv missing columns: {missing}"
        assert not extra,   f"monthly_summary.csv has extra columns: {extra}"

    def test_monthly_summary_row_count(self):
        """monthly_summary.csv must have exactly 3 rows — one per reporting month."""
        df = load_monthly()
        assert len(df) == 3, (
            f"Expected 3 rows (one per month), got {len(df)}. "
            f"Check that months are not duplicated or missing."
        )

    def test_monthly_summary_totals_and_counts(self):
        """total_mrr_usd and account_count must match per-month aggregates from the parquet."""
        df = load_monthly().set_index("month")

        expected_totals = {
            "2026-01": (13459.58, 19),
            "2026-02": (10749.57, 14),
            "2026-03": (8340.04,  13),
        }
        errors = []
        for month, (exp_total, exp_count) in expected_totals.items():
            if month not in df.index:
                errors.append(f"  {month}: row missing from monthly_summary.csv")
                continue
            row = df.loc[month]
            actual_total = float(row["total_mrr_usd"])
            actual_count = int(row["account_count"])
            if abs(actual_total - exp_total) > TOLERANCE:
                errors.append(
                    f"  {month} total_mrr_usd: expected {exp_total}, got {actual_total}"
                )
            if actual_count != exp_count:
                errors.append(
                    f"  {month} account_count: expected {exp_count}, got {actual_count}"
                )
        assert not errors, "Monthly summary mismatches:\n" + "\n".join(errors)

    def test_monthly_summary_mom_changes(self):
        """mrr_change_usd and mrr_change_pct must be blank for Jan and correct for Feb/Mar.

        Jan has no prior month so both change fields must be null/NaN/blank.
        Feb: change = 10749.57 - 13459.58 = -2710.01; pct = -2710.01 / 13459.58 = -0.2013
        Mar: change = 8340.04 - 10749.57 = -2409.53; pct = -2409.53 / 10749.57 = -0.2242

        Tests that agents perform period-over-period computation from the monthly aggregates,
        not a fixed lookup. Requires building the parquet first, then deriving this file.
        """
        df = load_monthly().set_index("month")

        # January — no prior period, both fields must be null/NaN
        jan_change = df.loc["2026-01", "mrr_change_usd"]
        jan_pct    = df.loc["2026-01", "mrr_change_pct"]
        assert pd.isna(jan_change) or jan_change == "", (
            f"2026-01 mrr_change_usd should be blank (no prior period), got {jan_change}"
        )
        assert pd.isna(jan_pct) or jan_pct == "", (
            f"2026-01 mrr_change_pct should be blank (no prior period), got {jan_pct}"
        )

        # February
        feb_change = float(df.loc["2026-02", "mrr_change_usd"])
        feb_pct    = float(df.loc["2026-02", "mrr_change_pct"])
        assert abs(feb_change - (-2710.01)) <= TOLERANCE, (
            f"2026-02 mrr_change_usd: expected -2710.01, got {feb_change}"
        )
        assert abs(feb_pct - (-0.2013)) <= 0.0001, (
            f"2026-02 mrr_change_pct: expected -0.2013, got {feb_pct}"
        )

        # March
        mar_change = float(df.loc["2026-03", "mrr_change_usd"])
        mar_pct    = float(df.loc["2026-03", "mrr_change_pct"])
        assert abs(mar_change - (-2409.53)) <= TOLERANCE, (
            f"2026-03 mrr_change_usd: expected -2409.53, got {mar_change}"
        )
        assert abs(mar_pct - (-0.2242)) <= 0.0001, (
            f"2026-03 mrr_change_pct: expected -0.2242, got {mar_pct}"
        )
